  #******************************** ODOO ***************************************************************************************************
  
  postgres:                                #base de donnée PostgreSQL de l'application Odoo       #ATTENTION changement à vérifier. ex db
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=${POSTGRES_USER_ODOO}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ODOO}
      - POSTGRES_DB=postgres
      - PGDATA=${PGDATA_ODOO}
    restart: always
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
      - ./volumes/postgresql/logs:/var/log/postgresql
      - ./volumes/postgresql/config:/etc/postgresql

  odoo17:                           # Application Wordpress Like, en bien plus solide et sécurisé, et permettant de déployer ERP / CRM / outil RH / outil Marketing automation (UTM) / outil E-Learning / etc.
    image: odoo:17
    user: root
    depends_on:
      - postgres   
    ports:
      - "${PORT_MNGT_ODOO}:8069" # port pour taper l'interface de management
      - "${PORT_LIVECHAT_ODOO}:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=${HOST_ODOO}       #ATTENTION changement à vérifier. ex db
      - USER=${USER_ODOO}
      - PASSWORD=${PASSWORD_ODOO}
    volumes:
      - ./volumes/Odoo/odoo-web-data-client:/var/lib/odoo
      - ./volumes/Odoo/addons:/mnt/extra-addons
      - ./volumes/Odoo/etc:/etc/odoo
      - ./volumes/Odoo/odoo_logs:/var/log/odoo:ro
    restart: always
