services:
  #******************************** PORTAINER ****************************************************************************************************

  portainer:  # Permet de visualiser et gérer vos conteneurs et volumes via une interface web simplifiée
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock  # obligatoire pour lier portainer à docker en local sur la machine
    ports:
      - "${PORT_MNGT_PORTAINER}:9443" # port pour taper l'interface de management
    volumes:
      - ${AUTOSTACK_PORTAINER_DIR:-..}/volumes/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro   #lie le docker.sock de l'hote au docker.sock du container. Permet à Portainer de voir la conf docker de l'hote
#      - ${AUTOSTACK_PORTAINER_DIR:-..}/volumes/portainer.key:/etc/portainer/portainer.key #à voir plus tard pour générer clé de chiffrement via entrypoint
    restart: unless-stopped
