global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  basic_auth:
    username: 'toto'
    password: 'changemeoryouilldie'
  static_configs:
  - targets:
    - <votre-serveur>:22190

- job_name: Uptime-kuma
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https                # attention http ou https ? That is the question !
  basic_auth:
    username: 'toto'
    password: 'changemeoryouilldie'
 static_configs:
  - targets:
    - <votre-serveur>:<port>
