services:
  prometheus:
    image: ${PROMETHEUS_IMAGE:?Définir PROMETHEUS_IMAGE}
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    ports:
      - "${PROMETHEUS_BIND_ADDRESS:-127.0.0.1}:${PROMETHEUS_PORT}:9090"
    volumes:
      - ${AUTOSTACK_PROM_GRAFANA_DIR:-..}/volumes/prometheus:/etc/prometheus:ro
      - prometheus_3_data:/prometheus
    security_opt:
      - no-new-privileges:true

  grafana:
    image: ${GRAFANA_IMAGE:?Définir GRAFANA_IMAGE}
    restart: unless-stopped
    ports:
      - "${GRAFANA_BIND_ADDRESS:-127.0.0.1}:${GRAFANA_PORT}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:?Définir GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:?Définir GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ${AUTOSTACK_PROM_GRAFANA_DIR:-..}/volumes/grafana:/etc/grafana/provisioning/datasources:ro
      - grafana_13_data:/var/lib/grafana
    security_opt:
      - no-new-privileges:true

volumes:
  prometheus_3_data:
  grafana_13_data:
