#!/bin/bash
set -e;

if [ -n "${POSTGRES_NON_ROOT_USER_N8N:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD_N8N:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER_N8N" --dbname "$POSTGRES_DB_N8N" <<-EOSQL
		CREATE USER ${POSTGRES_NON_ROOT_USER_N8N} WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD_N8N}';
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB_N8N} TO ${POSTGRES_NON_ROOT_USER_N8N};
		GRANT CREATE ON SCHEMA public TO ${POSTGRES_NON_ROOT_USER_N8N};
	EOSQL
else
	echo "SETUP INFO: No Environment variables given!"
fi
