#################################################### GRAPHANA OSS ###################################################################

  grafana-oss:
    image: grafana/grafana-oss
    container_name: grafana-oss
    restart: unless-stopped
    ports:
      - '${GRAPHANA_PORT}:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:
