services:

  #******************************** PORTAINER ****************************************************************************************************

  portainer:  # Permet de visualiser et gérer vos conteneurs et volumes via une interface web simplifiée
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock  # obligatoire pour lier portainer à docker en local sur la machine
    ports:
      - "22090:9443" # port pour taper l'interface de management
    volumes:
      - ./volumes/Portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock   #lie le docker.sock de l'hote au docker.sock du container. Permet à Portainer de voir la conf docker de l'hote
#      - ./volumes/Portainer/portainer.key:/etc/portainer/portainer.key #à voir plus tard pour générer clé de chiffrement via entrypoint (permet d'éviter erreur certificat autisigné quand on se connecte via https://IP:22090). Si besoin pour créer à la mano : dans terminal hote tapper 'openssl genrsa -out ./volumes/Portainer/portainer.key 2048'
    restart: unless-stopped
