services:
  #***************************************************************NEXTCLOUD*******************************************************************

  db-nextcloud:
    image: postgres:16
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NEXTCLOUD}
      POSTGRES_USER: ${POSTGRES_USER_NEXTCLOUD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_NEXTCLOUD}

  nextcloud:
    image: nextcloud:latest
    restart: always
    ports:
      - ${NEXTCLOUD_PORT}:80
    volumes:
      - ./volumes/Nextcloud/nextcloud:/var/www/html  #attention ici on copie tous le dossier, peut vite grossir et double la taille dès qu'on ajoute des fichiers (répertoire data)
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NEXTCLOUD}
      POSTGRES_USER: ${POSTGRES_USER_NEXTCLOUD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_NEXTCLOUD}
      NEXTCLOUD_ADMIN_USER: ${POSTGRES_ADMIN_USER_NEXTCLOUD}
      NEXTCLOUD_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD_NEXTCLOUD}

volumes:
  db_data:
  nextcloud:

networks:
  cloud:
    name: cloud
    driver: bridge
