#***************************************************************NEXTCLOUD*******************************************************************

  db-nextcloud:
    image: postgres:16
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud

  nextcloud:
    image: nextcloud:latest
    restart: always
    ports:
      - 42280:80
    volumes:
      - ./volumes/Nextcloud/nextcloud:/var/www/html
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
      NEXTCLOUD_ADMIN_USER: nextcloud
      NEXTCLOUD_ADMIN_PASSWORD: nextcloud
  # credential à utiliser lors de la première connexion, bien cliquer sur le bouton PostgreSQL et entrer : Database User: nextcloud / Database Password: nextcloud / Database Name: nextcloud / Database Host: db-nextcloud:5432

volumes:
  db_data:
  nextcloud:

networks:
  cloud:
    name: cloud
    driver: bridge
