input {
  http {
    id => "apisix_http_logger"
    host => "0.0.0.0"
    port => 8080
    codec => json
    response_code => 204
  }
}

filter {
  mutate {
    add_field => {
      "[@metadata][target_index]" => "apisix-demo-%{+YYYY.MM.dd}"
      "[event][dataset]" => "apisix.access"
      "[service][type]" => "apisix"
    }
  }
}

output {
  elasticsearch {
    id => "apisix_elasticsearch"
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
  stdout {
    codec => dots
  }
}
